import test from 'node:test';import assert from 'node:assert/strict';
import {analyzeLeg,analyzeMatch,alternativeRows,csvText,describe,wilson,codePattern} from '../public/mastermind/analytics.js';
import {createInitialState,applyAction,scoreGuess,encodeGuess} from '../public/mastermind/rules.js';
const row=(secret,guess)=>({guessId:encodeGuess(guess),guess,...scoreGuess(secret,guess)});
test('analysis checks all 1,296 alternatives and nonnegative regrets',()=>{const a=analyzeLeg([row([1,1,2,2],[0,0,1,1])]);assert.equal(a.rows[0].candidatesBefore,1296);assert.ok(a.rows[0].informationRegretBits>=0);assert.ok(a.rows[0].expectedRegret>=0);assert.ok(a.rows[0].worstCaseRegret>=0);assert.equal(a.rows[0].feedbackBuckets.reduce((s,b)=>s+b.count,0),1296);});
test('realized information telescopes to total uncertainty reduction',()=>{const secret=[1,1,2,2],a=analyzeLeg([row(secret,[0,0,1,1]),row(secret,[1,1,2,2])]);assert.ok(Math.abs(a.rows.reduce((s,r)=>s+r.realizedInformationBits,0)-Math.log2(1296))<1e-10);assert.equal(a.summary.finalCandidates,1);});
test('repeated non-solving guess gains no new information',()=>{const r=row([1,1,2,2],[0,0,0,0]),a=analyzeLeg([r,r]);assert.equal(a.rows[1].repeated,true);assert.equal(a.rows[1].realizedInformationBits,0);assert.equal(a.summary.repeatedGuesses,1);});
test('empty transcript retains full entropy and null averages',()=>{const a=analyzeLeg([]);assert.equal(a.summary.finalCandidates,1296);assert.equal(a.summary.meanExpectedInformationBits,null);});
test('match analytics cannot expose active-game counterfactuals',()=>{assert.throws(()=>analyzeMatch(createInitialState({matchId:'x'}),{}),/after/);});
test('forfeit analytics does not invent a JEV score',()=>{const secrets={targetForHuman:[0,0,1,1],targetForJev:[0,1,2,3]},state=applyAction(createInitialState({matchId:'x'}),{type:'RESIGN',actor:'human'},secrets);const a=analyzeMatch(state,secrets);assert.equal(a.score.humanCost,11);assert.equal(a.score.jevCost,null);});
test('descriptive quantiles use linear interpolation and retain nulls for no observations',()=>{assert.equal(describe([]).p95,null);assert.equal(describe([1,2,3,4]).p50,2.5);assert.equal(describe([1,2,3,4]).max,4);});
test('Wilson interval is bounded and explicitly null for no observations',()=>{assert.equal(wilson(0,0),null);assert.ok(wilson(0,10).lower>=0);assert.ok(wilson(10,10).upper<=1);});
test('code pattern classification covers repeated-symbol structures',()=>{assert.equal(codePattern([0,0,0,0]),'4');assert.equal(codePattern([0,0,1,1]),'2+2');assert.equal(codePattern([0,1,2,3]),'1+1+1+1');});
test('CSV quotes nested values and neutralizes spreadsheet formulas',()=>{const text=csvText([{name:'=HYPERLINK("x")',nested:{a:1},comma:'a,b',missing:null}]);assert.ok(text.includes("'=HYPERLINK"));assert.ok(text.includes('"a,b"'));assert.equal(csvText([]),'');});

test('all-alternative export includes 1296 rows per played turn and selected flag',()=>{let state=createInitialState({matchId:'alternatives'});const secrets={targetForHuman:[0,0,0,0],targetForJev:[1,1,1,1]};state=applyAction(state,{type:'GUESS',actor:'human',guess:[0,0,0,0]},secrets);state=applyAction(state,{type:'RESIGN',actor:'human'},secrets);const rows=alternativeRows(state);assert.equal(rows.length,1296);assert.equal(rows.filter(r=>r.selected).length,1);assert.ok(rows.every(r=>r.feedbackBuckets.reduce((s,b)=>s+b.count,0)===1296));});
test('numeric negative CSV values remain numbers, while string formulas are escaped',()=>{const csv=csvText([{delta:-0.5,text:'-evil'}]);assert.ok(csv.includes('\"-0.5\"'));assert.ok(csv.includes("'-evil"));});
