import test from 'node:test';import assert from 'node:assert/strict';
import { harness,createBody,actionBody,fakeJev } from './helpers.mjs';
import { getMatch,run,one } from '../server/db.js';
import { config } from '../server/security.js';
import { maintenance } from '../server/matches.js';
async function create(h,overrides={}){const r=await h.request('/api/matches',{method:'POST',body:createBody(overrides)});assert.equal(r.status,201,JSON.stringify(r.data));return r.data;}
async function advance(h,m,action){const r=await h.request('/api/matches/'+m.matchId+'/actions',{method:'POST',body:actionBody(m.revision,action)});assert.equal(r.status,200,JSON.stringify(r.data));return r.data;}
async function finish(h,m){const stored=await getMatch(h.db,m.matchId);m=await advance(h,m,{type:'GUESS',guess:stored.secrets.targetForHuman});while(m.phase==='jev_break')m=await advance(h,m,{type:'STEP_JEV'});return m;}
test('guest session has HTTP-only cookie and production security headers',async()=>{const h=await harness();try{const r=await h.request('/api/me');assert.equal(r.status,200);assert.ok(h.getCookie().startsWith('jev_local='));assert.ok(r.response.headers.get('Content-Security-Policy').includes("script-src 'self'"));assert.equal(r.response.headers.get('Cache-Control'),'no-store');}finally{h.close();}});
test('match creation keeps secret and salts private',async()=>{const h=await harness();try{const m=await create(h);assert.equal(m.phase,'human_break');assert.equal('reveal'in m,false);assert.equal('secrets'in m,false);assert.equal('secrets_json'in m,false);assert.equal('humanTargetSalt'in m,false);assert.equal(m.eligible,false);assert.equal(m.commitments.targetForHuman.length,64);}finally{h.close();}});
test('creation retries are idempotent and reject body mismatch',async()=>{const h=await harness();try{const body=createBody(),a=await h.request('/api/matches',{method:'POST',body}),b=await h.request('/api/matches',{method:'POST',body});assert.equal(a.data.matchId,b.data.matchId);const c=await h.request('/api/matches',{method:'POST',body:{...body,difficulty:'hard'}});assert.equal(c.status,409);}finally{h.close();}});
test('duplicate human HTTP action consumes exactly one guess',async()=>{const h=await harness();try{const m=await create(h),body=actionBody(0,{type:'GUESS',guess:[5,5,5,5]}),path='/api/matches/'+m.matchId+'/actions';const a=await h.request(path,{method:'POST',body}),b=await h.request(path,{method:'POST',body});assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(b.data.duplicate,true);assert.equal(b.data.legs.human.history.length,1);const c=await h.request(path,{method:'POST',body:{...body,action:{type:'GUESS',guess:[4,4,4,4]}}});assert.equal(c.status,409);}finally{h.close();}});
test('parallel actions cannot both apply against one revision',async()=>{const h=await harness();try{const m=await create(h),path='/api/matches/'+m.matchId+'/actions';const responses=await Promise.all([h.request(path,{method:'POST',body:actionBody(0,{type:'GUESS',guess:[5,5,5,5]})}),h.request(path,{method:'POST',body:actionBody(0,{type:'GUESS',guess:[4,4,4,4]})})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);assert.equal((await getMatch(h.db,m.matchId)).state.legs.human.history.length,1);}finally{h.close();}});
test('CSRF, cross-origin mutation, and client-forged actor are blocked',async()=>{const h=await harness();try{assert.equal((await h.request('/api/matches',{method:'POST',body:createBody(),headers:{'X-CSRF-Token':'wrong'}})).status,403);assert.equal((await h.request('/api/matches',{method:'POST',body:createBody(),headers:{Origin:'https://evil.test'}})).status,403);const m=await create(h);assert.equal((await h.request('/api/matches/'+m.matchId+'/actions',{method:'POST',body:actionBody(0,{type:'GUESS',actor:'jev',guess:[0,1,2,3]})})).status,422);}finally{h.close();}});
test('browser-supplied community identity and score endpoints are rejected',async()=>{const h=await harness();try{assert.equal((await h.request('/api/matches',{method:'POST',body:createBody({guildId:'111111111111111111'})})).status,422);assert.equal((await h.request('/api/score',{method:'POST',body:{score:9999}})).status,404);}finally{h.close();}});
test('active-match analytics and replay are withheld',async()=>{const h=await harness();try{const m=await create(h);for(const operation of ['analytics','replay'])assert.equal((await h.request('/api/matches/'+m.matchId+'/'+operation)).status,409);}finally{h.close();}});
test('full local-server match verifies replay and exposes analysis only at completion',async()=>{const h=await harness();try{const m=await finish(h,await create(h));assert.equal(m.phase,'complete');assert.equal(m.verified,true);assert.equal(m.eligible,false);assert.ok(m.decisions.every(d=>d.source==='local'));const a=await h.request('/api/matches/'+m.matchId+'/analytics');assert.equal(a.status,200);assert.equal(a.data.comparison,'selected_guess_only');assert.equal(a.data.human.rows[0].exact,4);assert.equal((await h.request('/api/matches/'+m.matchId+'/replay')).status,200);const profile=await h.request('/api/analytics/me');assert.equal(profile.data.totals.completed,1);assert.equal(profile.data.groups[0].games,1);}finally{h.close();}});
test('guest cannot request ranked eligibility',async()=>{const h=await harness();try{assert.equal((await h.request('/api/matches',{method:'POST',body:createBody({ranked:true})})).status,403);}finally{h.close();}});
test('production-mode authenticated JEV result can rank',async()=>{const h=await harness({production:true,provider:fakeJev()});try{await h.signIn();const m=await finish(h,await create(h,{ranked:true}));assert.equal(m.verified,true);assert.equal(m.eligible,true);assert.ok(m.decisions.some(d=>d.source==='jev'));const leaders=await h.request('/api/leaderboards');assert.equal(leaders.status,200,JSON.stringify(leaders.data));assert.equal(leaders.data.rows.length,1);assert.equal(leaders.data.rows[0].games,1);assert.equal(leaders.data.rows[0].established,0);}finally{h.close();}});
test('a provider fallback excludes the entire match from ranked standings',async()=>{const h=await harness({production:true,provider:fakeJev({failure:429})});try{await h.signIn();const m=await finish(h,await create(h,{ranked:true}));assert.equal(m.verified,true);assert.equal(m.eligible,false);assert.ok(m.decisions.some(d=>d.source==='fallback'));assert.equal((await h.request('/api/leaderboards')).data.rows.length,0);}finally{h.close();}});
test('only one active ranked match per account',async()=>{const h=await harness({production:true,provider:fakeJev()});try{await h.signIn();await create(h,{ranked:true});assert.equal((await h.request('/api/matches',{method:'POST',body:createBody({ranked:true})})).status,409);}finally{h.close();}});
test('resignation records a verified forfeit without fabricating JEV cost',async()=>{const h=await harness({production:true,provider:fakeJev()});try{await h.signIn();let m=await create(h,{ranked:true});m=await advance(h,m,{type:'RESIGN'});assert.equal(m.phase,'forfeit');assert.equal(m.eligible,true);const row=await getMatch(h.db,m.matchId);assert.equal(row.human_cost,11);assert.equal(row.jev_cost,null);}finally{h.close();}});
test('scheduled maintenance expires human leg, not a waiting JEV leg',async()=>{const h=await harness();try{const a=await create(h);await run(h.db,'UPDATE matches SET expires_at=? WHERE id=?',Date.now()-1000,a.matchId);await maintenance(h.db,config(h.env),h.env);assert.equal((await getMatch(h.db,a.matchId)).phase,'forfeit');let b=await create(h);b=await advance(h,b,{type:'GUESS',guess:(await getMatch(h.db,b.matchId)).secrets.targetForHuman});await run(h.db,'UPDATE matches SET expires_at=? WHERE id=?',Date.now()-1000,b.matchId);await maintenance(h.db,config(h.env),h.env);assert.equal((await getMatch(h.db,b.matchId)).phase,'jev_break');}finally{h.close();}});
test('stale lease recovery does not duplicate provider calls',async()=>{let calls=0;const h=await harness({production:true,provider:async(...a)=>{calls++;return fakeJev()(...a);}});try{await h.signIn();let m=await create(h,{ranked:true});m=await advance(h,m,{type:'GUESS',guess:(await getMatch(h.db,m.matchId)).secrets.targetForHuman});await run(h.db,'UPDATE matches SET pending_json=? WHERE id=?',JSON.stringify({leaseId:'old',requestId:'old-request',requestHash:'old',expiresAt:Date.now()-1,reservedAttempts:2}),m.matchId);m=await advance(h,m,{type:'STEP_JEV'});assert.equal(calls,0);assert.equal(m.evidence.source,'fallback');assert.equal(m.eligible,false);assert.equal(m.evidence.unobservedReservedAttempts,2);}finally{h.close();}});
test('two concurrent JEV requests apply one leased action only',async()=>{let calls=0;const h=await harness({production:true,provider:async(...args)=>{calls++;await new Promise(r=>setTimeout(r,30));return fakeJev()(...args);}});try{await h.signIn();let m=await create(h,{ranked:true});m=await advance(h,m,{type:'GUESS',guess:(await getMatch(h.db,m.matchId)).secrets.targetForHuman});const path='/api/matches/'+m.matchId+'/actions';const result=await Promise.all([h.request(path,{method:'POST',body:actionBody(m.revision,{type:'STEP_JEV'})}),h.request(path,{method:'POST',body:actionBody(m.revision,{type:'STEP_JEV'})})]);assert.ok(result.some(r=>r.status===200));assert.ok(result.some(r=>r.status===202));assert.equal(calls,1);assert.equal((await getMatch(h.db,m.matchId)).state.legs.jev.history.length,1);}finally{h.close();}});
test('another session cannot read a match or its revealed replay',async()=>{const h=await harness();try{const m=await create(h);const other=await h.request('/api/matches/'+m.matchId,{headers:{Cookie:'jev_local='+randomHex()}});assert.equal(other.status,401);}finally{h.close();}});
function randomHex(){return 'a'.repeat(64);}
test('oversized and malformed request bodies fail safely',async()=>{const h=await harness();try{assert.equal((await h.request('/api/matches',{method:'POST',body:'{'})).status,400);assert.equal((await h.request('/api/matches',{method:'POST',body:'x'.repeat(20000)})).status,413);}finally{h.close();}});
test('admin analytics is not exposed to ordinary sessions',async()=>{const h=await harness();try{assert.equal((await h.request('/api/admin/analytics')).status,403);h.env.ANALYTICS_ADMIN_TOKEN='test-admin-secret';assert.equal((await h.request('/api/admin/analytics',{headers:{Authorization:'Bearer test-admin-secret'}})).status,200);}finally{h.close();}});
test('structured events never contain secrets or raw provider credentials',async()=>{const h=await harness();try{const m=await finish(h,await create(h));const rows=await h.db.prepare('SELECT data_json FROM analytics_events').all();const text=JSON.stringify(rows);assert.equal(text.includes('humanTargetSalt'),false);assert.equal(text.includes('targetForHuman'),false);assert.equal(text.includes('Authorization'),false);assert.equal(text.includes('203.0.113.8'),false);}finally{h.close();}});
