import test from 'node:test';import assert from 'node:assert/strict';
import {harness} from './helpers.mjs';import {run,one} from '../server/db.js';
import {randomToken,sha256} from '../public/mastermind/verify.js';
import {redeemContext,verifyInteraction} from '../server/discord.js';
import {quota,event} from '../server/db.js';
import {openDatabase} from '../server/node-db.mjs';
const hex=bytes=>Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join('');
async function signedRequest(payload,keypair,timestamp=String(Math.floor(Date.now()/1000))){const body=JSON.stringify(payload),signature=await crypto.subtle.sign('Ed25519',keypair.privateKey,new TextEncoder().encode(timestamp+body));return new Request('https://game.test/api/discord/interactions',{method:'POST',headers:{'X-Signature-Timestamp':timestamp,'X-Signature-Ed25519':hex(signature)},body});}
test('OAuth requests identify only and uses single-use state',async()=>{const h=await harness({production:true});try{const r=await h.request('/api/auth/discord');assert.equal(r.status,302);const url=new URL(r.response.headers.get('location'));assert.equal(url.searchParams.get('scope'),'identify');const state=url.searchParams.get('state');assert.equal(state.length,64);const bad=await h.request('/api/auth/discord/callback?code=abc&state='+randomToken());assert.equal(bad.status,400);const cancel=await h.request('/api/auth/discord/callback?error=access_denied&state='+state);assert.equal(cancel.status,302);assert.equal((await h.request('/api/auth/discord/callback?code=abc&state='+state)).status,400);}finally{h.close();}});
test('OAuth callback rotates the session and discards provider tokens',async()=>{const h=await harness({production:true});try{const before=h.getCookie(),start=await h.request('/api/auth/discord'),state=new URL(start.response.headers.get('location')).searchParams.get('state');h.setFetch(async url=>url.endsWith('/oauth2/token')?Response.json({access_token:'not-persisted',refresh_token:'not-persisted-refresh'}):Response.json({id:'123456789123456789',username:'safe-test',global_name:'<script>bad()</script>'}));const result=await h.request('/api/auth/discord/callback?code=test&state='+state);assert.equal(result.status,302);assert.notEqual(h.getCookie(),before);const me=await h.request('/api/me');assert.equal(me.data.user.discord_user_id,'123456789123456789');const rows=await h.db.prepare('SELECT * FROM web_sessions').all();assert.equal(JSON.stringify(rows).includes('not-persisted'),false);}finally{h.close();}});
test('logout revokes the server-side session',async()=>{const h=await harness();try{const original=h.getCookie();assert.equal((await h.request('/api/logout',{method:'POST'})).status,200);const r=await h.request('/api/analytics/me',{headers:{Cookie:original}});assert.equal(r.status,401);}finally{h.close();}});
test('Discord signature verifies raw bytes and rejects mutations or stale timestamps',async()=>{const keys=await crypto.subtle.generateKey('Ed25519',true,['sign','verify']),pub=hex(await crypto.subtle.exportKey('raw',keys.publicKey));const request=await signedRequest({type:1},keys);assert.equal((await verifyInteraction(request,pub)).type,1);const signed=await signedRequest({type:1},keys),bad=new Request(signed.url,{method:'POST',headers:signed.headers,body:'{"type":2}'});await assert.rejects(verifyInteraction(bad,pub));await assert.rejects(verifyInteraction(await signedRequest({type:1},keys,'1000000000'),pub));});
test('launch ticket requires matching user, expires, and redeems only once',async()=>{const db=openDatabase();try{const ticket=randomToken(),hash=await sha256(ticket),now=Date.now(),token=randomToken();await run(db,'INSERT INTO users(discord_user_id,display_name,created_at,last_seen_at) VALUES(?,?,?,?)','111111111111111111','A',now,now);await run(db,'INSERT INTO web_sessions(token_hash,owner_key,discord_user_id,csrf,created_at,expires_at) VALUES(?,?,?,?,?,?)',token,'owner','111111111111111111','csrf',now,now+10000);await run(db,'INSERT INTO launch_tickets(token_hash,interaction_id,expected_user_id,guild_id,channel_id,created_at,expires_at) VALUES(?,?,?,?,?,?,?)',hash,'123456789123456789','111111111111111111','222222222222222222','333333333333333333',now,now+5000);await assert.rejects(redeemContext(ticket,{discord_user_id:'444444444444444444',token_hash:token},db));const session={discord_user_id:'111111111111111111',token_hash:token};const context=await redeemContext(ticket,session,db);assert.equal(context.guildId,'222222222222222222');await assert.rejects(redeemContext(ticket,session,db));}finally{db.close();}});
test('community access is denied without a fresh verified context',async()=>{const h=await harness({production:true});try{await h.signIn();assert.equal((await h.request('/api/leaderboards?scope=channel')).status,403);assert.equal((await h.request('/api/analytics/overview?scope=server')).status,403);}finally{h.close();}});
test('atomic quota cannot be bypassed by parallel requests',async()=>{const db=openDatabase();try{const r=await Promise.allSettled(Array.from({length:15},()=>quota(db,'test',5,60000)));assert.equal(r.filter(x=>x.status==='fulfilled').length,5);assert.equal(r.filter(x=>x.status==='rejected').length,10);}finally{db.close();}});
test('event metadata uses a strict allowlist',async()=>{const db=openDatabase();try{await event(db,'human_action','m',{turn:1,secrets:'bad',email:'bad',token:'bad',source:'human'});const row=await one(db,'SELECT data_json FROM analytics_events');assert.deepEqual(JSON.parse(row.data_json),{turn:1,source:'human'});}finally{db.close();}});
