import test from 'node:test';import assert from 'node:assert/strict';
import {assertCode,encodeGuess,decodeGuess,scoreGuess,createInitialState,applyAction,getJevView,getPublicView,isTerminal,makeReplay,reconstructReplay,parseActionId,actionId} from '../public/mastermind/rules.js';
import {randomToken,createCommitments,verifyReplay} from '../public/mastermind/verify.js';
const secrets={targetForHuman:[0,0,1,1],targetForJev:[0,1,2,3],humanTargetSalt:randomToken(),jevTargetSalt:randomToken()};
function initial(){return createInitialState({matchId:'test',difficulty:'normal'});}
test('all 1,296 code and action-ID round trips',()=>{for(let i=0;i<1296;i++){assert.equal(encodeGuess(decodeGuess(i)),i);assert.equal(parseActionId(actionId(i)),i);}});
test('reject invalid codes and IDs',()=>{for(const code of [null,[],[0,1,2],[0,1,2,6],['0',1,2,3],[0,1,2,NaN]])assert.throws(()=>assertCode(code));for(const id of [-1,1296,1.1,NaN])assert.throws(()=>decodeGuess(id));assert.throws(()=>parseActionId('g:1'));});
test('duplicate-aware feedback fixtures',()=>{assert.deepEqual(scoreGuess([0,0,1,1],[0,1,0,1]),{exact:2,misplaced:2});assert.deepEqual(scoreGuess([0,0,1,1],[0,0,0,0]),{exact:2,misplaced:0});assert.deepEqual(scoreGuess([0,0,1,1],[2,2,3,3]),{exact:0,misplaced:0});assert.deepEqual(scoreGuess([0,1,2,3],[0,1,2,3]),{exact:4,misplaced:0});});
test('two first-guess solves draw and lock terminal state',()=>{let s=applyAction(initial(),{type:'GUESS',actor:'human',guess:secrets.targetForHuman},secrets);assert.equal(s.phase,'jev_break');s=applyAction(s,{type:'GUESS',actor:'jev',guess:secrets.targetForJev,source:'jev'},secrets);assert.equal(s.outcome,'draw');assert.ok(isTerminal(s));assert.throws(()=>applyAction(s,{type:'RESIGN',actor:'human'},secrets));});
test('ten failures advance the leg and still allow a JEV win',()=>{let s=initial();for(let i=0;i<10;i++)s=applyAction(s,{type:'GUESS',actor:'human',guess:[5,5,5,5]},secrets);assert.equal(s.legs.human.status,'failed');s=applyAction(s,{type:'GUESS',actor:'jev',guess:secrets.targetForJev,source:'local'},secrets);assert.equal(s.outcome,'loss');});
test('tenth-guess solve is a solve, not a failure',()=>{let s=initial();for(let i=0;i<9;i++)s=applyAction(s,{type:'GUESS',actor:'human',guess:[5,5,5,5]},secrets);s=applyAction(s,{type:'GUESS',actor:'human',guess:secrets.targetForHuman},secrets);assert.equal(s.legs.human.solvedAt,10);assert.equal(s.legs.human.status,'solved');});
test('both players failing produces draw',()=>{let s=initial();for(const actor of ['human','jev'])for(let i=0;i<10;i++)s=applyAction(s,{type:'GUESS',actor,guess:[5,5,5,5],source:'local'},secrets);assert.equal(s.outcome,'draw');});
test('repeated guesses are legal separate moves',()=>{let s=initial();s=applyAction(s,{type:'GUESS',actor:'human',guess:[5,5,5,5]},secrets);s=applyAction(s,{type:'GUESS',actor:'human',guess:[5,5,5,5]},secrets);assert.equal(s.legs.human.history.length,2);});
test('reject wrong actor, forged action type and missing AI source',()=>{assert.throws(()=>applyAction(initial(),{type:'GUESS',actor:'jev',guess:[0,0,0,0],source:'jev'},secrets));assert.throws(()=>applyAction(initial(),{type:'WIN',actor:'human'},secrets));const s=applyAction(initial(),{type:'GUESS',actor:'human',guess:secrets.targetForHuman},secrets);assert.throws(()=>applyAction(s,{type:'GUESS',actor:'jev',guess:secrets.targetForJev},secrets));});
test('reducer does not mutate inputs',()=>{const s=initial(),before=JSON.stringify(s);applyAction(s,{type:'GUESS',actor:'human',guess:[0,0,0,0]},secrets);assert.equal(JSON.stringify(s),before);});
test('JEV projection never receives the human transcript or code',()=>{const s=applyAction(initial(),{type:'GUESS',actor:'human',guess:secrets.targetForHuman},secrets);const v=getJevView({...s,secrets});assert.deepEqual(v.history,[]);assert.equal('secrets'in v,false);assert.equal('outcome'in v,false);assert.equal('legs'in v,false);});
test('browser projection withholds reveal until match terminal',()=>{assert.equal('reveal'in getPublicView(initial(),secrets),false);const s=applyAction(initial(),{type:'RESIGN',actor:'human'},secrets);assert.deepEqual(getPublicView(s,secrets).reveal,secrets);});
test('full replay verifies commitments and detects tampering',async()=>{let s=createInitialState({matchId:'test',commitments:await createCommitments('test',secrets)});s=applyAction(s,{type:'GUESS',actor:'human',guess:secrets.targetForHuman},secrets);s=applyAction(s,{type:'GUESS',actor:'jev',guess:secrets.targetForJev,source:'jev'},secrets);const r=makeReplay(s,secrets);assert.deepEqual(reconstructReplay(r),s);assert.equal((await verifyReplay(r)).valid,true);const bad=structuredClone(r);bad.reveal.humanTargetSalt=randomToken();await assert.rejects(verifyReplay(bad),/Commitment/);const forged=structuredClone(r);forged.expectedOutcome='win';assert.throws(()=>reconstructReplay(forged));});
test('forfeit replay preserves actual action history',async()=>{const s=applyAction(createInitialState({matchId:'test',commitments:await createCommitments('test',secrets)}),{type:'RESIGN',actor:'human'},secrets);assert.equal((await verifyReplay(makeReplay(s,secrets))).state.outcome,'loss');});
